let str='jspiders';
let st1=str.toLowerCase();
console.log(st1);
let st2=str.toUpperCase();
console.log(st2);
let st3=str.charAt(2);
console.log(st3);
let st4=str.indexOf('d',3);
console.log(st4);
let st5=str.concat(st1,st2);
console.log(st5);
let st6=str.includes('p',1);
console.log(st6);
let st7=str.replace('p','ii');
console.log(st7);
let st8=str.split('e');
console.log(st8);
let st9=str.substr(0,3);
console.log(st9);
let st10=str.search('d');
console.log(st10);
let st11=str.trim();
console.log(st11);

console.log("======================================")
let str2='Hi how are u?';
let tr1=str2.toLowerCase();
console.log(tr1);
let tr2=str2.toUpperCase();
console.log(tr2);
let tr3=str2.charAt(3);
console.log(tr3);
let tr4=str2.indexOf('w',3);
console.log(tr4);
let tr5=str2.concat(tr1,tr2);
console.log(tr5);
let tr6=str2.includes('p',1);
console.log(tr6);
let tr7=str2.replace('p','ii');
console.log(tr7);
let tr8=str2.split('e');
console.log(tr8);
let tr9=str2.substr(0,3);
console.log(tr9);
let tr10=str2.search('d');
console.log(tr10);
let tr11=str2.trim();
console.log(tr11);